import hou 
import sys

GAMEDEV_TOOLS_LOCATION = "C:\work\GameDevelopmentToolset"

PY_PANEL_LOCATION = GAMEDEV_TOOLS_LOCATION + "\python_panels"
SCRIPTS_LOCATION = GAMEDEV_TOOLS_LOCATION + "\scripts"
PYTHON_SCRIPTS_LOCATION = SCRIPTS_LOCATION + "\python"


HOUDINI_PATH = hou.getenv("HOUDINI_PATH", "$HIP;$HOUDINI_USER_PREF_DIR;$HFS/houdini;$HFS/bin")
hou.putenv("HOUDINI_PATH", HOUDINI_PATH + ";" + GAMEDEV_TOOLS_LOCATION)

HOUDINI_PYTHON_PANEL_PATH = hou.getenv("HOUDINI_PYTHON_PANEL_PATH", "$HOUDINI_USER_PREF_DIR/python_panels;$HFS/houdini/python_panels")
hou.putenv("HOUDINI_PYTHON_PANEL_PATH", HOUDINI_PYTHON_PANEL_PATH + ";" + PY_PANEL_LOCATION)

HOUDINI_SCRIPT_PATH = hou.getenv("HOUDINI_SCRIPT_PATH", "$HOUDINI_USER_PREF_DIR/scripts;$HFS/houdini/scripts")
hou.putenv("HOUDINI_SCRIPT_PATH", HOUDINI_SCRIPT_PATH + ";" + SCRIPTS_LOCATION)

sys.path.append(PYTHON_SCRIPTS_LOCATION)

hou.putenv("HOUDINI_NO_SPLASH", "1")